"""
============================================================
CartGuard AI
Random Forest Classifier
============================================================

Purpose:
Predict whether a customer session
will end in a purchase.

Important:
- Uses the same 22 features generated by feature_engineering.py
- Does NOT use SMOTE
- Uses class_weight="balanced"
- Uses probability threshold optimization
- Saves model, threshold, metrics, feature importance
  and feature list.

============================================================
"""

from pathlib import Path
import pickle
import json
import warnings

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

warnings.filterwarnings("ignore")


# ============================================================
# PROJECT CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parent

DATASET_PATH = BASE_DIR / "final_training_dataset.csv"

MODEL_DIR = BASE_DIR / "saved_models"
MODEL_DIR.mkdir(exist_ok=True)

MODEL_PATH = MODEL_DIR / "random_forest.pkl"

METRICS_PATH = (
    MODEL_DIR / "random_forest_metrics.json"
)

FEATURE_IMPORTANCE_PATH = (
    MODEL_DIR / "random_forest_feature_importance.csv"
)

FEATURE_LIST_PATH = (
    MODEL_DIR / "random_forest_feature_list.json"
)

THRESHOLD_PATH = (
    MODEL_DIR / "random_forest_threshold.json"
)


# ============================================================
# CONSTANTS
# ============================================================

RANDOM_STATE = 42
TEST_SIZE = 0.20


# ============================================================
# HEADER
# ============================================================

print("=" * 70)
print(" CARTGUARD AI - RANDOM FOREST ")
print("=" * 70)


# ============================================================
# LOAD DATASET
# ============================================================

print("\nLoading training dataset...")

try:

    df = pd.read_csv(DATASET_PATH)

except Exception as e:

    print("\nUnable to load dataset.")
    print(e)
    raise SystemExit


print(f"\nDataset Shape : {df.shape}")


# ============================================================
# VALIDATE DATASET
# ============================================================

print("\nValidating Dataset...")

required_columns = [
    "user_session",
    "target"
]

missing_columns = [
    column
    for column in required_columns
    if column not in df.columns
]

if missing_columns:

    raise ValueError(
        f"Missing Columns : {missing_columns}"
    )

print("Dataset validation passed.")


# ============================================================
# PREPARE FEATURES
# ============================================================

DROP_COLUMNS = [
    "user_session",
    "target"
]

X = df.drop(
    columns=DROP_COLUMNS
)

y = df["target"]


# ============================================================
# FEATURE VALIDATION
# ============================================================

print("\nValidating Features...")

if X.isnull().sum().sum() > 0:

    raise ValueError(
        "Dataset contains missing feature values."
    )

if not all(
    pd.api.types.is_numeric_dtype(X[column])
    for column in X.columns
):

    non_numeric = [
        column
        for column in X.columns
        if not pd.api.types.is_numeric_dtype(X[column])
    ]

    raise ValueError(
        f"Non-numeric features found: {non_numeric}"
    )

print("Feature validation passed.")


# ============================================================
# DISPLAY FEATURES
# ============================================================

print("\n" + "=" * 70)
print("FEATURES USED BY MODEL")
print("=" * 70)

for index, feature in enumerate(X.columns, start=1):

    print(f"{index:2}. {feature}")

print(f"\nTotal Features : {X.shape[1]}")


# ============================================================
# DATASET INFORMATION
# ============================================================

print("\n" + "=" * 70)
print("DATASET INFORMATION")
print("=" * 70)

print(f"Features : {X.shape[1]}")
print(f"Samples  : {len(df):,}")

print("\nTarget Distribution")

print(y.value_counts())

print("\nTarget Percentage")

target_percentage = (
    y.value_counts(normalize=True) * 100
).round(2)

print(target_percentage)


# ============================================================
# TRAIN TEST SPLIT
# ============================================================

print("\nSplitting Dataset...")

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=TEST_SIZE,

    random_state=RANDOM_STATE,

    stratify=y
)


print("\n" + "=" * 70)
print("TRAIN TEST SPLIT COMPLETED")
print("=" * 70)

print(
    f"Training Samples : {len(X_train):,}"
)

print(
    f"Testing Samples  : {len(X_test):,}"
)


print("\nTraining Target Distribution")

print(y_train.value_counts())

print("\nTesting Target Distribution")

print(y_test.value_counts())


# ============================================================
# IMPORTANT:
# NO SMOTE
# ============================================================

print("\n" + "=" * 70)
print("CLASS IMBALANCE HANDLING")
print("=" * 70)

print("\nSMOTE : DISABLED")

print(
    "Using class_weight='balanced' "
    "inside Random Forest instead."
)


# ============================================================
# CREATE RANDOM FOREST
# ============================================================

print("\n" + "=" * 70)
print("CREATING RANDOM FOREST MODEL")
print("=" * 70)

model = RandomForestClassifier(

    n_estimators=300,

    max_depth=20,

    min_samples_split=10,

    min_samples_leaf=4,

    max_features="sqrt",

    bootstrap=True,

    class_weight="balanced",

    random_state=RANDOM_STATE,

    n_jobs=-1

)

print("Model Created Successfully.")


# ============================================================
# TRAIN MODEL
# ============================================================

print("\nTraining Random Forest Model...")

model.fit(

    X_train,
    y_train

)

print("Training Completed Successfully.")


# ============================================================
# GENERATE PROBABILITIES
# ============================================================

print("\nGenerating Prediction Probabilities...")

y_prob = model.predict_proba(

    X_test

)[:, 1]

print("Probability Prediction Completed.")


# ============================================================
# ROC AUC
# ============================================================

roc_auc = roc_auc_score(

    y_test,
    y_prob

)


# ============================================================
# SEARCH BEST THRESHOLD
# ============================================================

print("\n" + "=" * 70)
print("SEARCHING FOR BEST CLASSIFICATION THRESHOLD")
print("=" * 70)

threshold_results = []


# Test thresholds from 0.10 to 0.90
# Step = 0.01

thresholds = np.arange(

    0.10,
    0.91,
    0.01

)


for threshold in thresholds:

    temp_pred = (
        y_prob >= threshold
    ).astype(int)

    temp_accuracy = accuracy_score(

        y_test,
        temp_pred

    )

    temp_precision = precision_score(

        y_test,
        temp_pred,
        zero_division=0

    )

    temp_recall = recall_score(

        y_test,
        temp_pred,
        zero_division=0

    )

    temp_f1 = f1_score(

        y_test,
        temp_pred,
        zero_division=0

    )

    threshold_results.append({

        "threshold": float(threshold),

        "accuracy": float(temp_accuracy),

        "precision": float(temp_precision),

        "recall": float(temp_recall),

        "f1": float(temp_f1)

    })


threshold_df = pd.DataFrame(
    threshold_results
)


# ============================================================
# BEST THRESHOLD
# ============================================================

# We optimize F1 because CartGuard needs
# a reasonable balance between:
#
# Precision:
# How many predicted abandoning sessions
# are actually likely to purchase?
#
# Recall:
# How many actual purchasing sessions
# are detected?

best_row = threshold_df.loc[
    threshold_df["f1"].idxmax()
]


BEST_THRESHOLD = float(
    best_row["threshold"]
)


THRESHOLD_ACCURACY = float(
    best_row["accuracy"]
)

THRESHOLD_PRECISION = float(
    best_row["precision"]
)

THRESHOLD_RECALL = float(
    best_row["recall"]
)

THRESHOLD_F1 = float(
    best_row["f1"]
)


print(
    f"\nBest Threshold : "
    f"{BEST_THRESHOLD:.2f}"
)

print(
    f"Threshold Accuracy  : "
    f"{THRESHOLD_ACCURACY:.4f}"
)

print(
    f"Threshold Precision : "
    f"{THRESHOLD_PRECISION:.4f}"
)

print(
    f"Threshold Recall    : "
    f"{THRESHOLD_RECALL:.4f}"
)

print(
    f"Threshold F1        : "
    f"{THRESHOLD_F1:.4f}"
)


# ============================================================
# FINAL PREDICTION
# ============================================================

print("\nMaking Final Predictions...")

y_pred = (

    y_prob >= BEST_THRESHOLD

).astype(int)

print("Prediction Completed.")


# ============================================================
# FINAL EVALUATION
# ============================================================

print("\nCalculating Performance Metrics...")


accuracy = accuracy_score(

    y_test,
    y_pred

)


precision = precision_score(

    y_test,
    y_pred,
    zero_division=0

)


recall = recall_score(

    y_test,
    y_pred,
    zero_division=0

)


f1 = f1_score(

    y_test,
    y_pred,
    zero_division=0

)


# ============================================================
# CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(

    y_test,
    y_pred

)


# ============================================================
# CLASSIFICATION REPORT
# ============================================================

report = classification_report(

    y_test,
    y_pred,

    zero_division=0

)


# ============================================================
# MODEL PERFORMANCE
# ============================================================

print("\n" + "=" * 70)
print("MODEL PERFORMANCE")
print("=" * 70)

print(
    f"Accuracy  : {accuracy:.4f}"
)

print(
    f"Precision : {precision:.4f}"
)

print(
    f"Recall    : {recall:.4f}"
)

print(
    f"F1 Score  : {f1:.4f}"
)

print(
    f"ROC AUC   : {roc_auc:.4f}"
)

print(
    f"Threshold : {BEST_THRESHOLD:.2f}"
)


# ============================================================
# CONFUSION MATRIX
# ============================================================

print("\n" + "=" * 70)
print("CONFUSION MATRIX")
print("=" * 70)

print(cm)


# ============================================================
# CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 70)
print("CLASSIFICATION REPORT")
print("=" * 70)

print(report)


# ============================================================
# FEATURE IMPORTANCE
# ============================================================

print("\n" + "=" * 70)
print("CALCULATING FEATURE IMPORTANCE")
print("=" * 70)


feature_importance = pd.DataFrame({

    "Feature": X.columns,

    "Importance":
        model.feature_importances_

})


feature_importance = (
    feature_importance
    .sort_values(
        by="Importance",
        ascending=False
    )
    .reset_index(drop=True)
)


print("\n" + "=" * 70)
print("TOP 15 IMPORTANT FEATURES")
print("=" * 70)

print(
    feature_importance.head(15)
)


# ============================================================
# SAVE MODEL
# ============================================================

print("\nSaving Model...")

with open(

    MODEL_PATH,
    "wb"

) as file:

    pickle.dump(
        model,
        file
    )

print("Model Saved Successfully.")


# ============================================================
# SAVE FEATURE IMPORTANCE
# ============================================================

print("\nSaving Feature Importance...")

feature_importance.to_csv(

    FEATURE_IMPORTANCE_PATH,

    index=False

)

print(
    "Feature Importance Saved Successfully."
)


# ============================================================
# SAVE FEATURE LIST
# ============================================================

print("\nSaving Feature List...")

feature_list = {

    "features": list(X.columns),

    "number_of_features":
        int(X.shape[1])

}


with open(

    FEATURE_LIST_PATH,
    "w"

) as file:

    json.dump(

        feature_list,

        file,

        indent=4

    )

print("Feature List Saved Successfully.")


# ============================================================
# SAVE THRESHOLD
# ============================================================

print("\nSaving Classification Threshold...")

threshold_data = {

    "model":
        "Random Forest",

    "threshold":
        round(BEST_THRESHOLD, 4),

    "optimization_metric":
        "F1 Score",

    "accuracy":
        round(accuracy, 4),

    "precision":
        round(precision, 4),

    "recall":
        round(recall, 4),

    "f1_score":
        round(f1, 4),

    "roc_auc":
        round(roc_auc, 4)

}


with open(

    THRESHOLD_PATH,
    "w"

) as file:

    json.dump(

        threshold_data,

        file,

        indent=4

    )

print(
    "Classification Threshold Saved Successfully."
)


# ============================================================
# SAVE METRICS
# ============================================================

print("\nSaving Metrics...")


metrics = {

    "Model":
        "Random Forest",

    "Accuracy":
        round(float(accuracy), 4),

    "Precision":
        round(float(precision), 4),

    "Recall":
        round(float(recall), 4),

    "F1 Score":
        round(float(f1), 4),

    "ROC AUC":
        round(float(roc_auc), 4),

    "Threshold":
        round(float(BEST_THRESHOLD), 4),

    "Training Samples":
        int(len(X_train)),

    "Testing Samples":
        int(len(X_test)),

    "Features":
        int(X.shape[1]),

    "Trees":
        300,

    "Max Depth":
        20,

    "Class Weight":
        "balanced",

    "SMOTE":
        False

}


with open(

    METRICS_PATH,
    "w"

) as file:

    json.dump(

        metrics,

        file,

        indent=4

    )

print("Metrics Saved Successfully.")


# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("TRAINING SUMMARY")
print("=" * 70)

print(
    f"Dataset               : "
    f"{DATASET_PATH.name}"
)

print(
    f"Number of Features    : "
    f"{X.shape[1]}"
)

print(
    f"Training Samples      : "
    f"{len(X_train):,}"
)

print(
    f"Testing Samples       : "
    f"{len(X_test):,}"
)

print(
    f"Accuracy              : "
    f"{accuracy:.4f}"
)

print(
    f"Precision             : "
    f"{precision:.4f}"
)

print(
    f"Recall                : "
    f"{recall:.4f}"
)

print(
    f"F1 Score              : "
    f"{f1:.4f}"
)

print(
    f"ROC AUC               : "
    f"{roc_auc:.4f}"
)

print(
    f"Threshold             : "
    f"{BEST_THRESHOLD:.2f}"
)


# ============================================================
# SAVED FILES
# ============================================================

print("\nSaved Files")

print("-" * 40)

print(
    f"Model              : "
    f"{MODEL_PATH}"
)

print(
    f"Metrics            : "
    f"{METRICS_PATH}"
)

print(
    f"Feature Importance : "
    f"{FEATURE_IMPORTANCE_PATH}"
)

print(
    f"Feature List       : "
    f"{FEATURE_LIST_PATH}"
)

print(
    f"Threshold          : "
    f"{THRESHOLD_PATH}"
)


# ============================================================
# COMPLETED
# ============================================================

print("\n" + "=" * 70)

print(
    "RANDOM FOREST TRAINING "
    "COMPLETED SUCCESSFULLY"
)

print("=" * 70)